
// null
#pragma prolog { (predicate (result-of (osl#null) (? _))) }
~~~
(define-inline (osl#null) #f)
~~~
macro null {[null] = [identifier!(osl#null)()]}

// maybe-like matching on optionals
#pragma prolog {
  (predicate (match-on (osl#ctor#Some T) (? T)))
  (predicate (match-on (osl#ctor#Nothing) (? T)))
}
#pragma match-translation-rule {
  (match-pattern . (osl#ctor#Some T))
  (type-pattern . (? T))
  (predicate . osl#?->bool)
  (unpack . identity)
}
