
// null
#pragma prolog { (predicate (result-of (osl#null) (? _))) }
#pragma scheme-translator { (inline (define-inline (osl#null) #f)) }
macro null {[null] = [identifier!(osl#null)()]}

// maybe-like matching on optionals
#pragma prolog {
  (predicate (match-on (osl#ctor#Some T) (? T)))
  (predicate (match-on (osl#ctor#Nothing) (? T)))
}
#pragma scheme-translator {
  (cases-rule (osl#ctor#Some T) (? T) osl#?->bool identity)
}
