

foo() = { return 1, 2, "three" }
a, b, c = foo()
assert { a::num b::num c::str }
println("a=", a, ", b=", b, ", c=", c)


bar() = values(1, 2, "three")
// assert { bar() :: (num, num, str) }
a, b, c = bar()
assert { a::num b::num c::str }
println("a=", a, ", b=", b, ", c=", c)

// `return <expr>` does not care how many values expr emits
baz() = { return values(1, 2, 3) }
assert { baz() :: num }
