#!/usr/bin/env -S ./install/bin/opium-osl -r


require "unittest"

unit_test_fixture s = "qwerty"

unit_test str = {
  test_equal str(['q', 'w', 'e']) = "qwe"
  test_equal str(['q', 'w', 'e'].iter()) = "qwe"
}

unit_test iter = {
  test_equal_seqs iter("qwe") = ['q', 'w', 'e']
  test_equal_seqs iter("qwe", 1) = ['w', 'e']
  test_equal_seqs iter("qwe", 1, 2) = ['w']
  test_equal_seqs iter("qwe", 1, -1) = ['w', 'e']
}

unit_test copy(s) = {
  test_equal copy(s) = s
  test_not_eq copy(s) = s
  test_equal copy(s, 1, 3) = s[1:3]
}

unit_test concat = {
  test_equal concat("qwe", "asd", "zxc") = "qweasdzxc"
  test_equal concat("qwe") = "qwe"
  test_equal concat() = ""
}

unit_test (+) = {
  test_equal "qwe" + "asd" = "qweasd"
}

unit_test ref = {
  test_equal "qwe"[1] = 'w'
}

unit_test identifier!(set) = {
  s = "qwe"
  set s[1] = '@'
  test_equal s = "q@e"
}

unit_test substr = {
  s = "qweasd"
  test_equal substr(s, 0, 3) = "qwe"
  test_equal substr(s, 3, 6) = "asd"
  test_equal substr(s, 3, -1) = substr(s, 3, length(s))
  test_not_eq substr(s, 0, 3) = substr(s, 0, 3)
}

unit_test ref_range = {
  s = "qweasd"
  test_equal s[0:3] = "qwe"
  test_equal s[3:6] = "asd"
  test_equal s[3:-1] = s[3:length(s)]
  test_not_eq s[0:3] = s[0:3]
}

unit_test view(s) = {
  test_equal view(s, 1, 3) = substr(s, 1, 3)
  test_eq view(s, 0, -1) = s
}

unit_test (==)(s) = {
  test_true 'a' == 'a'
  test_false 'a' == 'b'

  test_true s == s
  test_true s == copy(s)
  test_false s == s + "q"
}

unit_test (!=)(s) = {
  test_true 'a' != 'b'
  test_false 'a' != 'a'

  test_true s != s + "q"
  test_false s != s
}

unit_test (<) = {
  test_true 'a' < 'b'
  test_false 'b' < 'a'
  test_false 'a' < 'a'

  test_true "a" < "b"
  test_false "q" < "q"
  test_true "aq" < "bq"
  test_true "qa" < "qb"
  test_false "qb" < "qa"
  test_false "bq" < "aq"
}

unit_test (>) = {
  test_true 'b' > 'a'
  test_false 'a' > 'b'
  test_false 'a' > 'a'

  test_true "b" > "a"
  test_false "q" > "q"
  test_true "qb" > "qa"
  test_true "bq" > "aq"
  test_false "aq" > "bq"
  test_false "qa" > "qb"
}

unit_test (<=) = {
  test_true 'a' <= 'b'
  test_false 'b' <= 'a'
  test_true 'a' <= 'a'

  test_true "a" <= "b"
  test_true "q" <= "q"
  test_true "aq" <= "bq"
  test_true "qa" <= "qb"
  test_false "qb" <= "qa"
  test_false "bq" <= "aq"
}

unit_test (>=) = {
  test_true 'b' >= 'a'
  test_false 'a' >= 'b'
  test_true 'a' >= 'a'

  test_true "b" >= "a"
  test_true "q" >= "q"
  test_true "qb" >= "qa"
  test_true "bq" >= "aq"
  test_false "aq" >= "bq"
  test_false "qa" >= "qb"
}

unit_test length = {
  test_equal length("qwe") = 3
  test_equal length("") = 0
  test_equal length("\0") = 1
}

unit_test list = {
  test_equal list("qwe") = ['q', 'w', 'e']
  test_equal list("") = []
}

unit_test num = {
  test_equal num("42") = 42
  test_equal num("42.5") = 42.5
  test_equal num("42 ") = 0
  test_equal num(" 42") = 0
  test_equal num("") = 0
  test_equal num("asdf") = 0
  test_equal num("42asdf") = 0
  test_equal num("+inf.0") = scm { +inf.0 }
  test_equal num("-inf.0") = scm { -inf.0 }
}

unit_test char_from_num = {
  test_equal char(97) = 'a'
}

unit_test char_to_num = {
  test_equal num('a') = 97
}

unit_test chomp = {
  test_equal chomp("asd ") = "asd "
  test_equal chomp("asd\n") = "asd"
  test_equal chomp("asd \n") = "asd "
  test_equal chomp("asd \n\n\n") = "asd \n\n"
  test_equal chomp("asd_", "_") = "asd"
  test_equal chomp("asd123", "123") = "asd"
  test_equal chomp("asd___", "__") = "asd_"
  test_equal chomp("123", "123") = ""
}